"""add code auth tables

Revision ID: f714bb18793a
Revises: 0001_initial_tables
Create Date: 2026-04-17 19:09:45.004507

"""
from alembic import op
import sqlalchemy as sa



revision = 'f714bb18793a'
down_revision = '0001_initial_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_codes_code_hash'), 'access_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_access_codes_status'), 'access_codes', ['status'], unique=False)
    op.create_table('auth_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('access_code_id', sa.String(length=36), nullable=False),
    sa.Column('device_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_devices_access_code_id'), 'auth_devices', ['access_code_id'], unique=False)
    op.create_index(op.f('ix_auth_devices_device_token_hash'), 'auth_devices', ['device_token_hash'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('access_code_id', sa.String(length=36), nullable=False),
    sa.Column('auth_device_id', sa.String(length=36), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['auth_device_id'], ['auth_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_access_code_id'), 'auth_sessions', ['access_code_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_auth_device_id'), 'auth_sessions', ['auth_device_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_session_token_hash'), 'auth_sessions', ['session_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_sessions_session_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_auth_device_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_access_code_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_auth_devices_device_token_hash'), table_name='auth_devices')
    op.drop_index(op.f('ix_auth_devices_access_code_id'), table_name='auth_devices')
    op.drop_table('auth_devices')
    op.drop_index(op.f('ix_access_codes_status'), table_name='access_codes')
    op.drop_index(op.f('ix_access_codes_code_hash'), table_name='access_codes')
    op.drop_table('access_codes')
    # ### end Alembic commands ###
